# LambDynamicLights configuration.
# The dynamic lights mode
mode = "fancy"

# Light sources settings.
[light_sources]
	# Enables water-sensitive light sources check. This means that water-sensitive items will not light up when submerged in water.
	water_sensitive_check = true
	# Enable block entities light source.
	block_entities = true
	# Enable entities light source.
	entities = true
	# Enable first-person player light source.
	self = true
	# TNT lighting mode. May be off, simple or fancy.
	tnt = "off"
	# Creeper lighting mode. May be off, simple or fancy.
	creeper = "simple"

	[light_sources.settings]

		[light_sources.settings.entities]

			[light_sources.settings.entities.minecraft]
				axolotl = true
				egg = true
				zoglin = true
				allay = true
				llama = true
				bat = true
				husk = true
				experience_bottle = true
				rabbit = true
				firework_rocket = true
				silverfish = true
				giant = true
				drowned = true
				item = true
				goat = true
				horse = true
				vindicator = true
				minecart = true
				llama_spit = true
				mooshroom = true
				glow_item_frame = false
				snowball = true
				parrot = true
				lightning_bolt = true
				creeper = true
				ravager = true
				evoker_fangs = true
				chest_minecart = true
				tropical_fish = true
				slime = true
				pillager = true
				area_effect_cloud = true
				piglin = true
				blaze = true
				zombie = true
				ender_pearl = true
				guardian = true
				fireball = true
				wither_skull = true
				wolf = true
				zombie_villager = true
				tnt_minecart = true
				elder_guardian = true
				small_fireball = true
				boat = true
				strider = true
				cave_spider = true
				witch = true
				cod = true
				spider = true
				panda = true
				bee = true
				arrow = true
				cow = true
				magma_cube = true
				pig = true
				skeleton = true
				frog = true
				hoglin = true
				armor_stand = true
				experience_orb = true
				dolphin = true
				stray = true
				turtle = true
				wither_skeleton = true
				wandering_trader = true
				salmon = true
				vex = true
				piglin_brute = true
				ocelot = true
				furnace_minecart = true
				item_frame = true
				phantom = true
				ender_dragon = true
				evoker = true
				warden = true
				glow_squid = true
				squid = true
				enderman = true
				dragon_fireball = true
				chicken = true
				trader_llama = true
				donkey = true
				fox = true
				iron_golem = true
				zombified_piglin = true
				cat = true
				ghast = true
				sheep = true
				player = true
				pufferfish = true
				potion = true
				trident = true
				villager = true
				skeleton_horse = true
				fishing_bobber = true
				polar_bear = true
				hopper_minecart = true
				painting = true
				wither = true

			[light_sources.settings.entities.contenttweaks]
				player_head = true

			[light_sources.settings.entities.ratsmischief]
				rat = true

			[light_sources.settings.entities.expedition]
				flare = true
				airship = true

			[light_sources.settings.entities.twigs]
				pebble = true

			[light_sources.settings.entities.blast]
				dirt_bomb = true
				stripminer = true
				confetti_trigger_bomb = true
				amethyst_trigger_bomb = true
				diamond_bomb = true
				bomb = true
				diamond_trigger_bomb = true
				slime_trigger_bomb = true
				bonesburrier = true
				confetti_bomb = true
				frost_trigger_bomb = true
				trigger_bomb = true
				amethyst_shard = true
				slime_bomb = true
				amethyst_bomb = true
				pipe_bomb = true
				frost_bomb = true
				golden_bomb = true
				icicle = true

			[light_sources.settings.entities.impaled]
				elder_trident = true
				hellfork = true
				soulfork = true
				atlan = true

			[light_sources.settings.entities.pickyourpoison]
				poison_dart = true
				poison_dart_frog = true

			[light_sources.settings.entities.mason]
				soulmould = true
				bonefly = true

			[light_sources.settings.entities.mannequins]
				mannequin = true
				statue = true

			[light_sources.settings.entities.shitsandgigs]
				awful_explosion_entity = true
				symbol_platform_blue = true
				symbol_platform_red = true
				symbol_platform = true
				beachball = true

			[light_sources.settings.entities.amarite]
				pylon = true
				malignancy = true
				amarite_magnet = true
				amarite_disc = true

			[light_sources.settings.entities.creeperspores]
				creeperling = true

			[light_sources.settings.entities.tot]
				raven = true

			[light_sources.settings.entities.befoul]
				blot = true
				blot_head = true

			[light_sources.settings.entities.enchancement]
				brimstone = true
				ice_shard = true
				frozen_player = true
				grapple_fishing_bobber = true

			[light_sources.settings.entities.arsenal]
				blood_scythe = true
				anchorblade = true

			[light_sources.settings.entities.sit]
				entity_sit = true

			[light_sources.settings.entities.typlosid]
				butter = true
				obsidian_shard = true

			[light_sources.settings.entities.angling]
				anglerfish = true
				sunfish = true
				mahi_mahi = true
				sea_slug = true
				pelican = true
				anomalocaris = true
				nautilus = true
				seahorse = true
				crab = true
				bubble_eye = true
				catfish = true

